name: safely_net_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  args: ^2.0.0
  mongo_dart: ^0.7.4
  shelf_plus: ^1.0.1
  crypt: ^4.0.1
  dart_jsonwebtoken: ^2.4.0
  mailer: ^5.0.2
  socket_io: ^1.0.1
  email_validator: ^2.0.1

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
